# Generated by Django 3.2 on 2021-04-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='shows',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='category_user.tvshow'),
        ),
    ]
